BEGIN;

CREATE TABLE IF NOT EXISTS campaigns (
	id BIGSERIAL PRIMARY KEY,
	content_id BIGINT NOT NULL,
	target_amount NUMERIC(10, 2) NOT NULL,
	current_amount NUMERIC(10, 2) DEFAULT 0 NOT NULL,
	text TEXT NOT NULL,
	is_active BOOLEAN NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP,
	FOREIGN KEY (content_id) REFERENCES contents(id)
);

COMMIT;
