BEGIN;

CREATE TABLE IF NOT EXISTS contents (
	id BIGSERIAL PRIMARY KEY,
	user_id BIGSERIAL NOT NULL,
	ringtone_url TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
