BEGIN;

CREATE TABLE IF NOT EXISTS qr_codes (
	id BIGSERIAL PRIMARY KEY,
	content_id BIGINT NOT NULL,
	code VARCHAR(10) NOT NULL,
	bg_color CHAR(7) NOT NULL,
	qr_color CHAR(7) NOT NULL,
	text VARCHAR(25),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP,
	FOREIGN KEY (content_id) REFERENCES contents(id)
);

COMMIT;
